FROM node:20-alpine

WORKDIR /app

# Install ALL dependencies (including devDependencies)
COPY package.json package-lock.json* ./
RUN npm install

# Copy source
COPY . .

# Run in Dev mode
CMD ["npm", "run", "dev"]